#!/bin/bash
set -eu

if [[ $# -eq 0 ]]; then
    echo 'provide CSV file'
    exit 1
fi

FILE=$1

head -n1000 "${FILE}" | \
    tr [:upper:] [:lower:] | \
    tr ' ' '_' | \
    csvsql -i postgresql --no-constraints | \
    sed -E 's/(BOOLEAN|DECIMAL|INTEGER|VARCHAR)/TEXT/g'
